[
  {
    name: "Grass Starters",
    pokemon: [
      { name: "Bulbasaur" },
      { name: "Ivysaur" },
      { name: "Venusaur" },
      { name: "Chikorita" },
      { name: "Bayleef" },
      { name: "Meganium" },
      { name: "Treecko" },
      { name: "Grovyle" },
      { name: "Sceptile" },
      { name: "Turtwig" },
      { name: "Grotle" },
      { name: "Torterra" },
      { name: "Snivy" },
      { name: "Servine" },
      { name: "Serperior" },
      { name: "Chespin" },
      { name: "Quilladin" },
      { name: "Chesnaught" },
      { name: "Rowlet" },
      { name: "Dartrix" },
      { name: "Decidueye" },
      { name: "Grookey" },
      { name: "Thwackey" },
      { name: "Rilaboom" },
      { name: "Sprigatito" },
      { name: "Floragato" },
      { name: "Meowscarada" },
    ],
  },
  {
    name: "Fire Starters",
    pokemon: [
      { name: "Charmander" },
      { name: "Charmeleon" },
      { name: "Charizard" },
      { name: "Cyndaquil" },
      { name: "Quilava" },
      { name: "Typhlosion" },
      { name: "Torchic" },
      { name: "Combusken" },
      { name: "Blaziken" },
      { name: "Chimchar" },
      { name: "Monferno" },
      { name: "Infernape" },
      { name: "Tepig" },
      { name: "Pignite" },
      { name: "Emboar" },
      { name: "Fennekin" },
      { name: "Braixen" },
      { name: "Delphox" },
      { name: "Litten" },
      { name: "Torracat" },
      { name: "Incineroar" },
      { name: "Scorbunny" },
      { name: "Raboot" },
      { name: "Cinderace" },
      { name: "Fuecoco" },
      { name: "Crocalor" },
      { name: "Skeledirge" },
    ],
  },
  {
    name: "Water Starters",
    pokemon: [
      { name: "Squirtle" },
      { name: "Wartortle" },
      { name: "Blastoise" },
      { name: "Totodile" },
      { name: "Croconaw" },
      { name: "Feraligatr" },
      { name: "Mudkip" },
      { name: "Marshtomp" },
      { name: "Swampert" },
      { name: "Piplup" },
      { name: "Prinplup" },
      { name: "Empoleon" },
      { name: "Oshawott" },
      { name: "Dewott" },
      { name: "Samurott" },
      { name: "Froakie" },
      { name: "Frogadier" },
      { name: "Greninja" },
      { name: "Popplio" },
      { name: "Brionne" },
      { name: "Primarina" },
      { name: "Sobble" },
      { name: "Drizzile" },
      { name: "Inteleon" },
      { name: "Quaxly" },
      { name: "Quaxwell" },
      { name: "Quaquaval" },
    ],
  },
  {
    name: "Pikachus",
    pokemon: [
      { name: "Pikachu" },
      { name: "Raichu" },
      { name: "Pichu" },
      { name: "Marill" },
      { name: "Azumarill" },
      { name: "Plusle" },
      { name: "Minun" },
      { name: "Pachirisu" },
      { name: "Azurill" },
      { name: "Emolga" },
      { name: "Dedenne" },
      { name: "Mimikyu" },
      { name: "Togedemaru" },
      { name: "Morpeko" },
      { name: "Pawmi" },
      { name: "Pawmo" },
      { name: "Pawmot" },
    ],
  },
  {
    name: "Eeveelutions",
    pokemon: [
      { name: "Vaporeon" },
      { name: "Jolteon" },
      { name: "Flareon" },
      { name: "Umbreon" },
      { name: "Espeon" },
      { name: "Leafeon" },
      { name: "Glaceon" },
      { name: "Sylveon" },
    ],
  },
  {
    name: "Insects",
    pokemon: [
      { name: "Caterpie" },
      { name: "Metapod" },
      { name: "Butterfree" },
      { name: "Ledyba" },
      { name: "Ledian" },
      { name: "Wurmple" },
      { name: "Silcoon" },
      { name: "Cascoon" },
      { name: "Beautifly" },
      { name: "Dustox" },
      { name: "Surskit" },
      { name: "Masquerain" },
      { name: "Volbeat" },
      { name: "Illumise" },
      { name: "Burmy" },
      { name: "Wormadam" },
      { name: "Mothim" },
      { name: "Kricketot" },
      { name: "Kricketune" },
      { name: "Sewaddle" },
      { name: "Swadloon" },
      { name: "Leavanny" },
      { name: "Scatterbug" },
      { name: "Spewpa" },
      { name: "Vivillon" },
      { name: "Grubbin" },
      { name: "Charjabug" },
      { name: "Vikavolt" },
      { name: "Blipbug" },
      { name: "Dottler" },
      { name: "Orbeetle" },
      { name: "Nymble" },
      { name: "Lokix" },
      { name: "Rellor" },
      { name: "Rabsca" },
    ],
  },
  {
    name: "Bees",
    pokemon: [
      { name: "Combee" },
      { name: "Vespiquen" },
      { name: "Cutiefly" },
      { name: "Ribombee" },
    ],
  },
  {
    name: "Dragonflies",
    pokemon: [
      { name: "Yanma" },
      { name: "Yanmega" },
      { name: "Trapinch" },
      { name: "Vibrava" },
      { name: "Flygon" },
    ],
  },
  {
    name: "Moths",
    pokemon: [
      { name: "Venonat" },
      { name: "Venomoth" },
      { name: "Larvesta" },
      { name: "Volcarona" },
      { name: "Snom" },
      { name: "Frosmoth" },
    ],
  },
  {
    name: "War Bugs",
    pokemon: [
      { name: "Pinsir" },
      { name: "Scyther" },
      { name: "Heracross" },
      { name: "Scizor" },
      { name: "Nincada" },
      { name: "Ninjask" },
      { name: "Shedinja" },
      { name: "Pawniard" },
      { name: "Bisharp" },
      { name: "Wimpod" },
      { name: "Golisopod" },
      { name: "Kleavor" },
      { name: "Kingambit" },
    ],
  },
  {
    name: "Ants",
    pokemon: [{ name: "Durant" }],
  },
  {
    name: "Arachnids",
    pokemon: [
      { name: "Spinarak" },
      { name: "Ariados" },
      { name: "Joltik" },
      { name: "Galvantula" },
      { name: "Dewpider" },
      { name: "Araquanid" },
      { name: "Tarountula" },
      { name: "Spidops" },
    ],
  },
  {
    name: "Centipedes",
    pokemon: [
      { name: "Venipede" },
      { name: "Whirlipede" },
      { name: "Scolipede" },
      { name: "Sizzlipede" },
      { name: "Centiskorch" },
    ],
  },
  {
    name: "Scorpions",
    pokemon: [
      { name: "Gligar" },
      { name: "Gliscor" },
      { name: "Skorupi" },
      { name: "Drapion" },
    ],
  },
  {
    name: "Flower Mantis",
    pokemon: [{ name: "Fomantis" }, { name: "Lurantis" }],
  },
  {
    name: "Flower Crown",
    pokemon: [{ name: "Comfey" }],
  },
  {
    name: "Flowers",
    pokemon: [
      { name: "Oddish" },
      { name: "Gloom" },
      { name: "Vileplume" },
      { name: "Hoppip" },
      { name: "Skiploom" },
      { name: "Jumpluff" },
      { name: "Bellossom" },
      { name: "Roselia" },
      { name: "Ralts" },
      { name: "Kirlia" },
      { name: "Gardevoir" },
      { name: "Budew" },
      { name: "Roserade" },
      { name: "Gallade" },
      { name: "Petilil" },
      { name: "Lilligant" },
      { name: "Flabébé" },
      { name: "Floette" },
      { name: "Florges" },
      { name: "Gossifleur" },
      { name: "Eldegoss" },
      { name: "Bounsweet" },
      { name: "Steenee" },
      { name: "Tsareena" },
      { name: "Smoliv" },
      { name: "Dolliv" },
      { name: "Arboliva" },
    ],
  },
  {
    name: "Seeds",
    pokemon: [
      { name: "Sunkern" },
      { name: "Sunflora" },
      { name: "Sudowoodo" },
      { name: "Seedot" },
      { name: "Nuzleaf" },
      { name: "Shiftry" },
      { name: "Bonsly" },
    ],
  },
  {
    name: "Aggro Seeds",
    pokemon: [
      { name: "Pineco" },
      { name: "Forretress" },
      { name: "Ferroseed" },
      { name: "Ferrothorn" },
    ],
  },
  {
    name: "Vines",
    pokemon: [
      { name: "Bellsprout" },
      { name: "Weepinbell" },
      { name: "Victreebel" },
      { name: "Tangela" },
      { name: "Tangrowth" },
    ],
  },
  {
    name: "Cactuses",
    pokemon: [
      { name: "Cacnea" },
      { name: "Cacturne" },
      { name: "Carnivine" },
      { name: "Maractus" },
    ],
  },
  {
    name: "Mushrooms",
    pokemon: [
      { name: "Paras" },
      { name: "Parasect" },
      { name: "Shroomish" },
      { name: "Breloom" },
      { name: "Foongus" },
      { name: "Amoonguss" },
      { name: "Morelull" },
      { name: "Shiinotic" },
    ],
  },
  {
    name: "Sweets",
    pokemon: [
      { name: "Vanillite" },
      { name: "Vanillish" },
      { name: "Vanilluxe" },
      { name: "Swirlix" },
      { name: "Slurpuff" },
      { name: "Spritzee" },
      { name: "Aromatisse" },
      { name: "Milcery" },
      { name: "Alcremie" },
    ],
  },
  {
    name: "Fruits",
    pokemon: [
      { name: "Cherubi" },
      { name: "Cherrim" },
      { name: "Tropius" },
      { name: "Applin" },
      { name: "Flapple" },
      { name: "Appletun" },
      { name: "Dipplin" },
      { name: "Hydrapple" },
    ],
  },
  {
    name: "Foods",
    pokemon: [
      { name: "Fidough" },
      { name: "Dachsbun" },
      { name: "Capsakid" },
      { name: "Scovillain" },
    ],
  },
  {
    name: "Birds",
    pokemon: [
      { name: "Pidgey" },
      { name: "Pidgeotto" },
      { name: "Pidgeot" },
      { name: "Spearow" },
      { name: "Fearow" },
      { name: "Farfetch'd" },
      { name: "Doduo" },
      { name: "Dodrio" },
      { name: "Hoothoot" },
      { name: "Noctowl" },
      { name: "Natu" },
      { name: "Xatu" },
      { name: "Murkrow" },
      { name: "Taillow" },
      { name: "Swellow" },
      { name: "Swablu" },
      { name: "Altaria" },
      { name: "Starly" },
      { name: "Staravia" },
      { name: "Staraptor" },
      { name: "Honchkrow" },
      { name: "Pidove" },
      { name: "Tranquill" },
      { name: "Unfezant" },
      { name: "Rufflet" },
      { name: "Braviary" },
      { name: "Vullaby" },
      { name: "Mandibuzz" },
      { name: "Fletchling" },
      { name: "Fletchinder" },
      { name: "Talonflame" },
      { name: "Pikipek" },
      { name: "Trumbeak" },
      { name: "Toucannon" },
      { name: "Rookidee" },
      { name: "Corvisquire" },
      { name: "Corviknight" },
      { name: "Sirfetch'd" },
      { name: "Bombirdier" },
    ],
  },
  {
    name: "Iron Birds",
    pokemon: [{ name: "Skarmory" }],
  },
  {
    name: "Water Birds",
    pokemon: [
      { name: "Psyduck" },
      { name: "Golduck" },
      { name: "Wingull" },
      { name: "Pelipper" },
      { name: "Ducklett" },
      { name: "Swanna" },
      { name: "Cramorant" },
      { name: "Wattrel" },
      { name: "Kilowattrel" },
      { name: "Flamigo" },
    ],
  },
  {
    name: "Parrots",
    pokemon: [
      { name: "Chatot" },
      { name: "Hawlucha" },
      { name: "Oricorio" },
      { name: "Squawkabilly" },
    ],
  },
  {
    name: "Bats",
    pokemon: [
      { name: "Zubat" },
      { name: "Golbat" },
      { name: "Crobat" },
      { name: "Woobat" },
      { name: "Swoobat" },
      { name: "Noibat" },
      { name: "Noivern" },
    ],
  },
  {
    name: "Rodents",
    pokemon: [
      { name: "Rattata" },
      { name: "Raticate" },
      { name: "Sandshrew" },
      { name: "Sandslash" },
      { name: "Nidoran♀" },
      { name: "Nidorina" },
      { name: "Nidoqueen" },
      { name: "Nidoran♂" },
      { name: "Nidorino" },
      { name: "Nidoking" },
      { name: "Sentret" },
      { name: "Furret" },
      { name: "Zigzagoon" },
      { name: "Linoone" },
      { name: "Bidoof" },
      { name: "Bibarel" },
      { name: "Patrat" },
      { name: "Watchog" },
      { name: "Stunky" },
      { name: "Skuntank" },
      { name: "Minccino" },
      { name: "Cinccino" },
      { name: "Yungoos" },
      { name: "Gumshoos" },
      { name: "Skwovet" },
      { name: "Greedent" },
      { name: "Obstagoon" },
      { name: "Tandemaus" },
      { name: "Maushold" },
    ],
  },
  {
    name: "Rabbits",
    pokemon: [
      { name: "Buneary" },
      { name: "Lopunny" },
      { name: "Bunnelby" },
      { name: "Diggersby" },
    ],
  },
  {
    name: "Moles",
    pokemon: [
      { name: "Diglett" },
      { name: "Dugtrio" },
      { name: "Drilbur" },
      { name: "Excadrill" },
    ],
  },
  {
    name: "Weasels",
    pokemon: [
      { name: "Sneasel" },
      { name: "Buizel" },
      { name: "Floatzel" },
      { name: "Weavile" },
      { name: "Zangoose" },
      { name: "Sneasler" },
    ],
  },
  {
    name: "Dogs",
    pokemon: [
      { name: "Growlithe" },
      { name: "Arcanine" },
      { name: "Houndour" },
      { name: "Houndoom" },
      { name: "Snubbull" },
      { name: "Granbull" },
      { name: "Poochyena" },
      { name: "Mightyena" },
      { name: "Lillipup" },
      { name: "Herdier" },
      { name: "Stoutland" },
      { name: "Furfrou" },
      { name: "Rockruff" },
      { name: "Lycanroc" },
      { name: "Maschiff" },
      { name: "Mabosstiff" },
      { name: "Greavard" },
      { name: "Houndstone" },
    ],
  },
  {
    name: "Electric Dogs",
    pokemon: [
      { name: "Electrike" },
      { name: "Manectric" },
      { name: "Shinx" },
      { name: "Luxio" },
      { name: "Luxray" },
      { name: "Yamper" },
      { name: "Boltund" },
    ],
  },
  {
    name: "Foxes",
    pokemon: [
      { name: "Vulpix" },
      { name: "Ninetales" },
      { name: "Nickit" },
      { name: "Thievul" },
    ],
  },
  {
    name: "Cats",
    pokemon: [
      { name: "Meowth" },
      { name: "Persian" },
      { name: "Skitty" },
      { name: "Delcatty" },
      { name: "Glameow" },
      { name: "Purugly" },
      { name: "Purrloin" },
      { name: "Liepard" },
      { name: "Espurr" },
      { name: "Meowstic" },
      { name: "Perrserker" },
    ],
  },
  {
    name: "Farmyard cattles",
    pokemon: [{ name: "Tauros" }, { name: "Miltank" }, { name: "Bouffalant" }],
  },
  {
    name: "Farmyard sheeps",
    pokemon: [
      { name: "Mareep" },
      { name: "Flaaffy" },
      { name: "Ampharos" },
      { name: "Cottonee" },
      { name: "Whimsicott" },
      { name: "Skiddo" },
      { name: "Gogoat" },
      { name: "Wooloo" },
      { name: "Dubwool" },
    ],
  },
  {
    name: "Farmyard pigs",
    pokemon: [
      { name: "Spoink" },
      { name: "Grumpig" },
      { name: "Lechonk" },
      { name: "Oinkologne" },
    ],
  },
  {
    name: "Farmyard equines",
    pokemon: [
      { name: "Ponyta" },
      { name: "Rapidash" },
      { name: "Mudbray" },
      { name: "Mudsdale" },
    ],
  },
  {
    name: "Cervids",
    pokemon: [
      { name: "Stantler" },
      { name: "Deerling" },
      { name: "Sawsbuck" },
      { name: "Wyrdeer" },
    ],
  },
  {
    name: "Wilds",
    pokemon: [
      { name: "Cubone" },
      { name: "Marowak" },
      { name: "Kangaskhan" },
      { name: "Rhyhorn" },
      { name: "Rhydon" },
      { name: "Girafarig" },
      { name: "Phanpy" },
      { name: "Donphan" },
      { name: "Rhyperior" },
      { name: "Hippopotas" },
      { name: "Hippowdon" },
      { name: "Blitzle" },
      { name: "Zebstrika" },
      { name: "Litleo" },
      { name: "Pyroar" },
      { name: "Komala" },
      { name: "Cufant" },
      { name: "Copperajah" },
      { name: "Farigiraf" },
    ],
  },
  {
    name: "Bears",
    pokemon: [
      { name: "Teddiursa" },
      { name: "Ursaring" },
      { name: "Cubchoo" },
      { name: "Beartic" },
      { name: "Pancham" },
      { name: "Pangoro" },
      { name: "Stufful" },
      { name: "Bewear" },
      { name: "Ursaluna" },
    ],
  },
  {
    name: "Monkeys",
    pokemon: [
      { name: "Mankey" },
      { name: "Primeape" },
      { name: "Aipom" },
      { name: "Ambipom" },
      { name: "Pansage" },
      { name: "Simisage" },
      { name: "Pansear" },
      { name: "Simisear" },
      { name: "Panpour" },
      { name: "Simipour" },
      { name: "Oranguru" },
      { name: "Passimian" },
      { name: "Annihilape" },
    ],
  },
  {
    name: "Snakes",
    pokemon: [
      { name: "Ekans" },
      { name: "Arbok" },
      { name: "Seviper" },
      { name: "Silicobra" },
      { name: "Sandaconda" },
    ],
  },
  {
    name: "Lizards",
    pokemon: [
      { name: "Scraggy" },
      { name: "Scrafty" },
      { name: "Sandile" },
      { name: "Krokorok" },
      { name: "Krookodile" },
      { name: "Helioptile" },
      { name: "Heliolisk" },
      { name: "Salandit" },
      { name: "Salazzle" },
    ],
  },
  {
    name: "Motor Lizards",
    pokemon: [{ name: "Cyclizar" }],
  },
  {
    name: "Motors",
    pokemon: [{ name: "Varoom" }, { name: "Revavroom" }],
  },
  {
    name: "Ugly Worms",
    pokemon: [{ name: "Orthworm" }],
  },
  {
    name: "Rocks",
    pokemon: [
      { name: "Geodude" },
      { name: "Graveler" },
      { name: "Golem" },
      { name: "Roggenrola" },
      { name: "Boldore" },
      { name: "Gigalith" },
      { name: "Golett" },
      { name: "Golurk" },
      { name: "Rolycoly" },
      { name: "Carkol" },
      { name: "Coalossal" },
      { name: "Stonjourner" },
      { name: "Nacli" },
      { name: "Naclstack" },
      { name: "Garganacl" },
    ],
  },
  {
    name: "Diamond Rocks",
    pokemon: [{ name: "Carbink" }],
  },
  {
    name: "Shells",
    pokemon: [
      { name: "Shellder" },
      { name: "Cloyster" },
      { name: "Karrablast" },
      { name: "Escavalier" },
      { name: "Shelmet" },
      { name: "Accelgor" },
    ],
  },
  {
    name: "Fossils",
    pokemon: [
      { name: "Kabuto" },
      { name: "Kabutops" },
      { name: "Omanyte" },
      { name: "Omastar" },
      { name: "Aerodactyl" },
      { name: "Lileep" },
      { name: "Cradily" },
      { name: "Anorith" },
      { name: "Armaldo" },
      { name: "Cranidos" },
      { name: "Rampardos" },
      { name: "Shieldon" },
      { name: "Bastiodon" },
      { name: "Tirtouga" },
      { name: "Carracosta" },
      { name: "Archen" },
      { name: "Archeops" },
      { name: "Amaura" },
      { name: "Aurorus" },
      { name: "Tyrunt" },
      { name: "Tyrantrum" },
      { name: "Dracozolt" },
      { name: "Arctozolt" },
      { name: "Dracovish" },
      { name: "Arctovish" },
    ],
  },
  {
    name: "Bladers",
    pokemon: [
      { name: "Honedge" },
      { name: "Doublade" },
      { name: "Aegislash" },
      { name: "Charcadet" },
      { name: "Armarouge" },
      { name: "Ceruledge" },
    ],
  },
  {
    name: "Units",
    pokemon: [
      { name: "Exeggcute" },
      { name: "Exeggutor" },
      { name: "Falinks" },
    ],
  },
  {
    name: "Fighters",
    pokemon: [
      { name: "Machop" },
      { name: "Machoke" },
      { name: "Machamp" },
      { name: "Hitmonlee" },
      { name: "Hitmonchan" },
      { name: "Tyrogue" },
      { name: "Hitmontop" },
      { name: "Makuhita" },
      { name: "Hariyama" },
      { name: "Mienfoo" },
      { name: "Mienshao" },
      { name: "Throh" },
      { name: "Sawk" },
    ],
  },
  {
    name: "Lazy Fighters",
    pokemon: [
      { name: "Slowpoke" },
      { name: "Slowbro" },
      { name: "Slowking" },
      { name: "Slakoth" },
      { name: "Vigoroth" },
      { name: "Slaking" },
      { name: "Timburr" },
      { name: "Gurdurr" },
      { name: "Conkeldurr" },
      { name: "Whismur" },
      { name: "Loudred" },
      { name: "Exploud" },
    ],
  },
  {
    name: "Psychic Fighters",
    pokemon: [
      { name: "Abra" },
      { name: "Kadabra" },
      { name: "Alakazam" },
      { name: "Meditite" },
      { name: "Medicham" },
      { name: "Darumaka" },
      { name: "Darmanitan" },
    ],
  },
  {
    name: "Psychic Tapirs",
    pokemon: [
      { name: "Drowzee" },
      { name: "Hypno" },
      { name: "Munna" },
      { name: "Musharna" },
    ],
  },
  {
    name: "Anteaters",
    pokemon: [{ name: "Heatmor" }],
  },
  {
    name: "Camels",
    pokemon: [{ name: "Numel" }, { name: "Camerupt" }],
  },
  {
    name: "Tortoises",
    pokemon: [
      { name: "Torkoal" },
      { name: "Turtonator" },
      { name: "Chewtle" },
      { name: "Drednaw" },
    ],
  },
  {
    name: "Frogs",
    pokemon: [
      { name: "Poliwag" },
      { name: "Poliwhirl" },
      { name: "Poliwrath" },
      { name: "Politoed" },
      { name: "Croagunk" },
      { name: "Toxicroak" },
      { name: "Tympole" },
      { name: "Palpitoad" },
      { name: "Seismitoad" },
      { name: "Tadbulb" },
      { name: "Bellibolt" },
    ],
  },
  {
    name: "Amphibians",
    pokemon: [
      { name: "Wooper" },
      { name: "Quagsire" },
      { name: "Wobbuffet" },
      { name: "Lotad" },
      { name: "Lombre" },
      { name: "Ludicolo" },
      { name: "Wynaut" },
      { name: "Clodsire" },
    ],
  },
  {
    name: "Slugs",
    pokemon: [
      { name: "Slugma" },
      { name: "Magcargo" },
      { name: "Shellos" },
      { name: "Gastrodon" },
    ],
  },
  {
    name: "Echinoderms",
    pokemon: [
      { name: "Staryu" },
      { name: "Starmie" },
      { name: "Binacle" },
      { name: "Barbaracle" },
      { name: "Mareanie" },
      { name: "Toxapex" },
      { name: "Pyukumuku" },
      { name: "Pincurchin" },
      { name: "Wiglett" },
      { name: "Wugtrio" },
    ],
  },
  {
    name: "Tentacles",
    pokemon: [
      { name: "Tentacool" },
      { name: "Tentacruel" },
      { name: "Remoraid" },
      { name: "Octillery" },
      { name: "Frillish" },
      { name: "Jellicent" },
      { name: "Inkay" },
      { name: "Malamar" },
      { name: "Clobbopus" },
      { name: "Grapploct" },
      { name: "Toedscool" },
      { name: "Toedscruel" },
    ],
  },
  {
    name: "Crustaceans",
    pokemon: [
      { name: "Krabby" },
      { name: "Kingler" },
      { name: "Corphish" },
      { name: "Crawdaunt" },
      { name: "Dwebble" },
      { name: "Crustle" },
      { name: "Clauncher" },
      { name: "Clawitzer" },
      { name: "Crabrawler" },
      { name: "Crabominable" },
      { name: "Klawf" },
    ],
  },
  {
    name: "Seahorses",
    pokemon: [
      { name: "Horsea" },
      { name: "Seadra" },
      { name: "Kingdra" },
      { name: "Skrelp" },
      { name: "Dragalge" },
    ],
  },
  {
    name: "Fishes",
    pokemon: [
      { name: "Magikarp" },
      { name: "Gyarados" },
      { name: "Goldeen" },
      { name: "Seaking" },
      { name: "Chinchou" },
      { name: "Lanturn" },
      { name: "Mantine" },
      { name: "Qwilfish" },
      { name: "Barboach" },
      { name: "Whiscash" },
      { name: "Carvanha" },
      { name: "Sharpedo" },
      { name: "Luvdisc" },
      { name: "Feebas" },
      { name: "Milotic" },
      { name: "Basculin" },
      { name: "Finneon" },
      { name: "Lumineon" },
      { name: "Mantyke" },
      { name: "Clamperl" },
      { name: "Huntail" },
      { name: "Gorebyss" },
      { name: "Relicanth" },
      { name: "Tynamo" },
      { name: "Eelektrik" },
      { name: "Eelektross" },
      { name: "Alomomola" },
      { name: "Bruxish" },
      { name: "Wishiwashi" },
      { name: "Arrokuda" },
      { name: "Barraskewda" },
      { name: "Overqwil" },
      { name: "Basculegion" },
      { name: "Dondozo" },
      { name: "Tatsugiri" },
      { name: "Finizen" },
      { name: "Palafin" },
      { name: "Veluza" },
    ],
  },
  {
    name: "Cetaceans",
    pokemon: [
      { name: "Wailmer" },
      { name: "Wailord" },
      { name: "Cetoddle" },
      { name: "Cetitan" },
    ],
  },
  {
    name: "Polars",
    pokemon: [
      { name: "Seel" },
      { name: "Dewgong" },
      { name: "Lapras" },
      { name: "Swinub" },
      { name: "Piloswine" },
      { name: "Delibird" },
      { name: "Spheal" },
      { name: "Sealeo" },
      { name: "Walrein" },
      { name: "Snover" },
      { name: "Abomasnow" },
      { name: "Mamoswine" },
      { name: "Snorunt" },
      { name: "Glalie" },
      { name: "Froslass" },
      { name: "Cryogonal" },
      { name: "Bergmite" },
      { name: "Avalugg" },
      { name: "Eiscue" },
    ],
  },
  {
    name: "Dumpsters",
    pokemon: [
      { name: "Koffing" },
      { name: "Weezing" },
      { name: "Grimer" },
      { name: "Muk" },
      { name: "Snorlax" },
      { name: "Munchlax" },
      { name: "Gulpin" },
      { name: "Swalot" },
      { name: "Trubbish" },
      { name: "Garbodor" },
    ],
  },
  {
    name: "Shapeshifters",
    pokemon: [
      { name: "Ditto" },
      { name: "Kecleon" },
      { name: "Castform" },
      { name: "Zorua" },
      { name: "Zoroark" },
    ],
  },
  {
    name: "Creepos",
    pokemon: [{ name: "Lickitung" }, { name: "Lickilicky" }],
  },
  {
    name: "Angelics",
    pokemon: [{ name: "Absol" }],
  },
  {
    name: "Pixies",
    pokemon: [
      { name: "Audino" },
      { name: "Indeedee" },
      { name: "Hatenna" },
      { name: "Hattrem" },
      { name: "Hatterene" },
      { name: "Impidimp" },
      { name: "Morgrem" },
      { name: "Grimmsnarl" },
      { name: "Tinkatink" },
      { name: "Tinkatuff" },
      { name: "Tinkaton" },
    ],
  },
  {
    name: "Babies",
    pokemon: [
      { name: "Clefairy" },
      { name: "Clefable" },
      { name: "Jigglypuff" },
      { name: "Wigglytuff" },
      { name: "Chansey" },
      { name: "Cleffa" },
      { name: "Igglybuff" },
      { name: "Togepi" },
      { name: "Togetic" },
      { name: "Togekiss" },
      { name: "Blissey" },
      { name: "Happiny" },
    ],
  },
  {
    name: "Strong Babies",
    pokemon: [
      { name: "Magmar" },
      { name: "Electabuzz" },
      { name: "Mr. Mime" },
      { name: "Jynx" },
      { name: "Magby" },
      { name: "Elekid" },
      { name: "Mime Jr." },
      { name: "Smoochum" },
      { name: "Magmortar" },
      { name: "Electivire" },
      { name: "Mr. Rime" },
      { name: "Toxel" },
      { name: "Toxtricity" },
    ],
  },
  {
    name: "Electric Balls",
    pokemon: [{ name: "Voltorb" }, { name: "Electrode" }],
  },
  {
    name: "Rock Snakes",
    pokemon: [{ name: "Onix" }, { name: "Steelix" }],
  },
  {
    name: "Magnetics",
    pokemon: [
      { name: "Magnemite" },
      { name: "Magneton" },
      { name: "Nosepass" },
      { name: "Magnezone" },
      { name: "Probopass" },
      { name: "Klink" },
      { name: "Klang" },
      { name: "Klinklang" },
    ],
  },
  {
    name: "Rings",
    pokemon: [{ name: "Klefki" }],
  },
  {
    name: "Bells",
    pokemon: [
      { name: "Chimecho" },
      { name: "Chingling" },
      { name: "Bronzor" },
      { name: "Bronzong" },
    ],
  },
  {
    name: "Cells",
    pokemon: [{ name: "Solosis" }, { name: "Duosion" }, { name: "Reuniclus" }],
  },
  {
    name: "Coins",
    pokemon: [{ name: "Gimmighoul" }, { name: "Gholdengo" }],
  },
  {
    name: "Aliens",
    pokemon: [
      { name: "Lunatone" },
      { name: "Solrock" },
      { name: "Rotom" },
      { name: "Elgyem" },
      { name: "Beheeyem" },
      { name: "Minior" },
      { name: "Glimmet" },
      { name: "Glimmora" },
    ],
  },
  {
    name: "Artists",
    pokemon: [{ name: "Smeargle" }, { name: "Shroodle" }, { name: "Grafaiai" }],
  },
  {
    name: "Virtuals",
    pokemon: [{ name: "Porygon" }, { name: "Porygon2" }, { name: "Porygon-Z" }],
  },
  {
    name: "Solos",
    pokemon: [
      { name: "Shuckle" },
      { name: "Dunsparce" },
      { name: "Corsola" },
      { name: "Spinda" },
      { name: "Stunfisk" },
      { name: "Cursola" },
      { name: "Dudunsparce" },
    ],
  },
  {
    name: "Spirit Toys",
    pokemon: [
      { name: "Shuppet" },
      { name: "Banette" },
      { name: "Baltoy" },
      { name: "Claydol" },
      { name: "Drifloon" },
      { name: "Drifblim" },
    ],
  },
  {
    name: "Ghost Plants",
    pokemon: [
      { name: "Phantump" },
      { name: "Trevenant" },
      { name: "Pumpkaboo" },
      { name: "Gourgeist" },
      { name: "Dhelmise" },
      { name: "Bramblin" },
      { name: "Brambleghast" },
    ],
  },
  {
    name: "Mysterious",
    pokemon: [
      { name: "Gastly" },
      { name: "Haunter" },
      { name: "Gengar" },
      { name: "Misdreavus" },
      { name: "Sableye" },
      { name: "Mismagius" },
      { name: "Mawile" },
      { name: "Litwick" },
      { name: "Lampent" },
      { name: "Chandelure" },
      { name: "Gothita" },
      { name: "Gothorita" },
      { name: "Gothitelle" },
      { name: "Sandygast" },
      { name: "Palossand" },
      { name: "Sinistea" },
      { name: "Polteageist" },
      { name: "Poltchageist" },
      { name: "Sinistcha" },
    ],
  },
  {
    name: "Egyptians",
    pokemon: [
      { name: "Unown" },
      { name: "Duskull" },
      { name: "Dusclops" },
      { name: "Dusknoir" },
      { name: "Spiritomb" },
      { name: "Yamask" },
      { name: "Cofagrigus" },
      { name: "Sigilyph" },
      { name: "Riolu" },
      { name: "Lucario" },
      { name: "Runerigus" },
      { name: "Flittle" },
      { name: "Espathra" },
    ],
  },
  {
    name: "Pseudo Dragons",
    pokemon: [
      { name: "Druddigon" },
      { name: "Drampa" },
      { name: "Duraludon" },
      { name: "Archaludon" },
    ],
  },
  {
    name: "Pseudo Leggos",
    pokemon: [
      { name: "Dratini" },
      { name: "Dragonair" },
      { name: "Dragonite" },
      { name: "Larvitar" },
      { name: "Pupitar" },
      { name: "Tyranitar" },
      { name: "Bagon" },
      { name: "Shelgon" },
      { name: "Salamence" },
      { name: "Beldum" },
      { name: "Metang" },
      { name: "Metagross" },
      { name: "Gible" },
      { name: "Gabite" },
      { name: "Garchomp" },
      { name: "Deino" },
      { name: "Zweilous" },
      { name: "Hydreigon" },
      { name: "Goomy" },
      { name: "Sligoo" },
      { name: "Goodra" },
      { name: "Jangmo-o" },
      { name: "Hakamo-o" },
      { name: "Kommo-o" },
      { name: "Dreepy" },
      { name: "Drakloak" },
      { name: "Dragapult" },
      { name: "Frigibax" },
      { name: "Arctibax" },
      { name: "Baxcalibur" },
    ],
  },
  {
    name: "Fake Pseudo Leggos",
    pokemon: [
      { name: "Aron" },
      { name: "Lairon" },
      { name: "Aggron" },
      { name: "Axew" },
      { name: "Fraxure" },
      { name: "Haxorus" },
    ],
  },
  {
    name: "Leggos",
    pokemon: [
      { name: "Mewtwo" },
      { name: "Lugia" },
      { name: "Ho-oh" },
      { name: "Latias" },
      { name: "Latios" },
      { name: "Dialga" },
      { name: "Palkia" },
      { name: "Heatran" },
      { name: "Regigigas" },
      { name: "Giratina" },
      { name: "Cresselia" },
      { name: "Type: Null" },
      { name: "Silvally" },
      { name: "Cosmog" },
      { name: "Cosmoem" },
      { name: "Solgaleo" },
      { name: "Lunala" },
      { name: "Necrozma" },
      { name: "Zacian" },
      { name: "Zamazenta" },
      { name: "Eternatus" },
      { name: "Kubfu" },
      { name: "Urshifu" },
      { name: "Koraidon" },
      { name: "Miraidon" },
      { name: "Ogerpon" },
      { name: "Terapagos" },
    ],
  },
  {
    name: "Legendary Trios",
    pokemon: [
      { name: "Articuno" },
      { name: "Zapdos" },
      { name: "Moltres" },
      { name: "Entei" },
      { name: "Raikou" },
      { name: "Suicune" },
      { name: "Kyogre" },
      { name: "Groudon" },
      { name: "Rayquaza" },
      { name: "Uxie" },
      { name: "Mesprit" },
      { name: "Azelf" },
      { name: "Cobalion" },
      { name: "Terrakion" },
      { name: "Virizion" },
      { name: "Reshiram" },
      { name: "Zekrom" },
      { name: "Kyurem" },
      { name: "Xerneas" },
      { name: "Yveltal" },
      { name: "Zygarde" },
      { name: "Calyrex" },
      { name: "Glastrier" },
      { name: "Spectrier" },
      { name: "Okidogi" },
      { name: "Munkidori" },
      { name: "Fezandipiti" },
    ],
  },
  {
    name: "Legendary Quartets",
    pokemon: [
      { name: "Thundurus" },
      { name: "Tornadus" },
      { name: "Landorus" },
      { name: "Tapu Koko" },
      { name: "Tapu Lele" },
      { name: "Tapu Bulu" },
      { name: "Tapu Fini" },
      { name: "Enamorus" },
      { name: "Chien-Pao" },
      { name: "Wo-Chien" },
      { name: "Ting-Lu" },
      { name: "Chi-Yu" },
    ],
  },
  {
    name: "Legendary Quintets",
    pokemon: [
      { name: "Regice" },
      { name: "Regirock" },
      { name: "Registeel" },
      { name: "Regieleki" },
      { name: "Regidrago" },
    ],
  },
  {
    name: "Mythicals",
    pokemon: [
      { name: "Deoxys" },
      { name: "Darkrai" },
      { name: "Shaymin" },
      { name: "Arceus" },
      { name: "Keldeo" },
      { name: "Meloetta" },
      { name: "Genesect" },
      { name: "Diancie" },
      { name: "Hoopa" },
      { name: "Volcanion" },
      { name: "Magearna" },
      { name: "Marshadow" },
      { name: "Zeraora" },
      { name: "Meltan" },
      { name: "Melmetal" },
      { name: "Zarude" },
      { name: "Pecharunt" },
    ],
  },
  {
    name: "Errants",
    pokemon: [
      { name: "Mew" },
      { name: "Celebi" },
      { name: "Jirachi" },
      { name: "Phione" },
      { name: "Manaphy" },
      { name: "Victini" },
    ],
  },
  {
    name: "Ultra Beasts",
    pokemon: [
      { name: "Nihilego" },
      { name: "Pheromosa" },
      { name: "Buzzwole" },
      { name: "Xurkitree" },
      { name: "Celesteela" },
      { name: "Kartana" },
      { name: "Guzzlord" },
      { name: "Poipole" },
      { name: "Naganadel" },
      { name: "Stakataka" },
      { name: "Blacephalon" },
    ],
  },
  {
    name: "Paradox",
    pokemon: [
      { name: "Great Tusk" },
      { name: "Flutter Mane" },
      { name: "Scream Tail" },
      { name: "Brute Bonnet" },
      { name: "Sandy Shocks" },
      { name: "Slither Wing" },
      { name: "Roaring Moon" },
      { name: "Iron Treads" },
      { name: "Iron Bundle" },
      { name: "Iron Hands" },
      { name: "Iron Thorns" },
      { name: "Iron Jugulis" },
      { name: "Iron Moth" },
      { name: "Iron Valiant" },
      { name: "Walking Wake" },
      { name: "Iron Leaves" },
      { name: "Raging Bolt" },
      { name: "Iron Crown" },
      { name: "Gouging Fire" },
      { name: "Iron Boulder" },
    ],
  },
];
